/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'border.radius.lg': '8px',
  'border.radius.md': '4px',
  'border.radius.sm': '2px',
  'border.width.lg': '4px',
  'border.width.md': '2px',
  'border.width.sm': '1px',
  'color.black': '#000000',
  'color.brand.interactive': '#0054e5',
  'color.brand.interactive-dark': '#0054e5',
  'color.brand.primary': '#a20000',
  'color.btn.link.bg': 'transparent',
  'color.btn.link.border': 'transparent',
  'color.btn.link.fg': '#000000',
  'color.btn.link.hover.fg': '#0054e5',
  'color.btn.primary.bg': '#0054e5',
  'color.btn.primary.border': '#0054e5',
  'color.btn.primary.fg': '#FFFFFF',
  'color.btn.primary.hover.bg': 'transparent',
  'color.btn.primary.hover.border': '#0054e5',
  'color.btn.primary.hover.fg': '#0054e5',
  'color.btn.secondary.bg': 'transparent',
  'color.btn.secondary.border': '#000000',
  'color.btn.secondary.fg': '#000000',
  'color.btn.secondary.hover.bg': '#000000',
  'color.btn.secondary.hover.border': '#000000',
  'color.btn.secondary.hover.fg': '#FFFFFF',
  'color.btn.tertiary.bg': '#000000',
  'color.btn.tertiary.border': '#000000',
  'color.btn.tertiary.fg': '#FFFFFF',
  'color.btn.tertiary.hover.bg': '#f5f5f5',
  'color.btn.tertiary.hover.border': '#000000',
  'color.btn.tertiary.hover.fg': '#000000',
  'color.feedback.error': '#dc3545',
  'color.feedback.info': '#17a2b8',
  'color.feedback.success': '#28a745',
  'color.feedback.warning': '#ffc107',
  'color.gray.100': '#f5f5f5',
  'color.gray.200': '#e5e5e5',
  'color.gray.300': '#b8b8b8',
  'color.gray.400': '#999999',
  'color.gray.500': '#888888',
  'color.gray.600': '#666666',
  'color.gray.700': '#333333',
  'color.gray.800': '#1a1a1a',
  'color.gray.900': '#0a0a0a',
  'color.theme.background.default': '#FFFFFF',
  'color.theme.background.surface': '#f5f5f5',
  'color.theme.border.default': '#666666',
  'color.theme.border.light': '#f5f5f5',
  'color.theme.state.disabled': '#b8b8b8',
  'color.theme.state.focus': '#0054e5',
  'color.theme.status.error-text': '#dc3545',
  'color.theme.status.success-bg': '#d4edda',
  'color.theme.text.muted': '#666666',
  'color.theme.text.primary': '#000000',
  'color.theme.text.secondary': '#333333',
  'color.white': '#FFFFFF',
  'max-width.default': '75rem',
  'max-width.medium': '50rem',
  'max-width.narrow': '20rem',
  'max-width.thin': '37.5rem',
  'space.lg': '2rem',
  'space.md': '1.5rem',
  'space.semantic.padding': '1rem',
  'space.sm': '1rem',
  'space.xl': '3rem',
  'space.xs': '0.75rem',
  'space.xxl': '4rem',
  'space.xxs': '0.5rem',
  'space.xxxl': '5rem',
  'space.xxxs': '0.25rem',
  'transition.duration.fast': '0.1s',
  'transition.duration.normal': '0.2s',
  'transition.duration.slow': '0.3s',
  'typography.font-family.body': ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  'typography.font-family.mono': ['monospace'],
  'typography.font-family.primary': ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  'typography.font-family.secondary': ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  'typography.font-size.btn.default': 'calc(1.15rem * var(--typography-font-size-scale))',
  'typography.font-size.btn.sm': 'calc(1rem * var(--typography-font-size-scale))',
  'typography.font-size.heading.1': 'calc(clamp(2rem, 4vw + 1rem, 3.5rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.2': 'calc(clamp(1.5rem, 3vw + 1rem, 3rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.3': 'calc(clamp(1.3rem, 2.5vw + 1rem, 2.5rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.4': 'calc(clamp(1.2rem, 2.5vw + 1rem, 2rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.5': 'calc(clamp(1.15rem, 2vw + 1rem, 1.4rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.6': 'calc(clamp(1.125rem, 1.8vw + 1rem, 1.25rem) * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.1': 'calc(1.1rem * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.2': 'calc(1rem * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.3': 'calc(0.95rem * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.4': 'calc(0.9rem * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.5': 'calc(0.85rem * var(--typography-font-size-scale))',
  'typography.font-size.scale': 1,
  'typography.font-weight.bold': 700,
  'typography.font-weight.bolder': 900,
  'typography.font-weight.lighter': 300,
  'typography.font-weight.normal': 400,
  'typography.letter-spacing.lg': '0.05rem',
  'typography.letter-spacing.md': '0.03rem',
  'typography.letter-spacing.sm': '0.02rem',
  'typography.letter-spacing.xl': '0.08rem',
  'typography.letter-spacing.xs': '0.01rem',
  'typography.letter-spacing.xxl': '0.1rem',
  'typography.line-height.lg': 1.6,
  'typography.line-height.md': 1.3,
  'typography.line-height.sm': 1.1,
  'typography.line-height.xl': 1.7,
  'typography.line-height.xs': 1,
};

export const meta = {
  'border.radius.lg': {
    _original: {
      $value: '8px',
    },
    _group: {
      id: 'border.radius',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.radius.lg',
    $type: 'dimension',
    $value: '8px',
  },
  'border.radius.md': {
    _original: {
      $value: '4px',
    },
    _group: {
      id: 'border.radius',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.radius.md',
    $type: 'dimension',
    $value: '4px',
  },
  'border.radius.sm': {
    _original: {
      $value: '2px',
    },
    _group: {
      id: 'border.radius',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.radius.sm',
    $type: 'dimension',
    $value: '2px',
  },
  'border.width.lg': {
    _original: {
      $value: '4px',
    },
    _group: {
      id: 'border.width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.width.lg',
    $type: 'dimension',
    $value: '4px',
  },
  'border.width.md': {
    _original: {
      $value: '2px',
    },
    _group: {
      id: 'border.width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.width.md',
    $type: 'dimension',
    $value: '2px',
  },
  'border.width.sm': {
    _original: {
      $value: '1px',
    },
    _group: {
      id: 'border.width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.width.sm',
    $type: 'dimension',
    $value: '1px',
  },
  'color.black': {
    _original: {
      $value: '#000000',
    },
    _group: {
      id: 'color',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.black',
    $type: 'color',
    $value: '#000000',
  },
  'color.brand.interactive': {
    _original: {
      $value: '#0054e5',
    },
    _group: {
      id: 'color.brand',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.brand.interactive',
    $type: 'color',
    $value: '#0054e5',
  },
  'color.brand.interactive-dark': {
    _original: {
      $value: '{color.brand.interactive}',
    },
    _group: {
      id: 'color.brand',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.brand.interactive-dark',
    $type: 'color',
    $value: '#0054e5',
  },
  'color.brand.primary': {
    _original: {
      $value: '#a20000',
    },
    _group: {
      id: 'color.brand',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.brand.primary',
    $type: 'color',
    $value: '#a20000',
  },
  'color.btn.link.bg': {
    _original: {
      $value: 'transparent',
    },
    _group: {
      id: 'color.btn.link',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.link.bg',
    $type: 'color',
    $value: 'transparent',
  },
  'color.btn.link.border': {
    _original: {
      $value: 'transparent',
    },
    _group: {
      id: 'color.btn.link',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.link.border',
    $type: 'color',
    $value: 'transparent',
  },
  'color.btn.link.fg': {
    _original: {
      $value: '{color.theme.text.primary}',
    },
    _group: {
      id: 'color.btn.link',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.link.fg',
    $type: 'color',
    $value: '#000000',
  },
  'color.btn.link.hover.fg': {
    _original: {
      $value: '{color.brand.interactive}',
    },
    _group: {
      id: 'color.btn.link.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.link.hover.fg',
    $type: 'color',
    $value: '#0054e5',
  },
  'color.btn.primary.bg': {
    _original: {
      $value: '{color.brand.interactive}',
      $extensions: {
        mode: {
          dark: '{color.brand.interactive-dark}',
        },
      },
    },
    _group: {
      id: 'color.btn.primary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.primary.bg',
    $type: 'color',
    $value: '#0054e5',
    $extensions: {
      mode: {
        dark: '#0054e5',
      },
    },
  },
  'color.btn.primary.border': {
    _original: {
      $value: '{color.btn.primary.bg}',
      $extensions: {
        mode: {
          dark: '{color.brand.interactive-dark}',
        },
      },
    },
    _group: {
      id: 'color.btn.primary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.primary.border',
    $type: 'color',
    $value: '#0054e5',
    $extensions: {
      mode: {
        dark: '#0054e5',
      },
    },
  },
  'color.btn.primary.fg': {
    _original: {
      $value: '{color.white}',
      $extensions: {
        mode: {
          dark: '{color.white}',
        },
      },
    },
    _group: {
      id: 'color.btn.primary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.primary.fg',
    $type: 'color',
    $value: '#FFFFFF',
    $extensions: {
      mode: {
        dark: '#FFFFFF',
      },
    },
  },
  'color.btn.primary.hover.bg': {
    _original: {
      $value: 'transparent',
    },
    _group: {
      id: 'color.btn.primary.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.primary.hover.bg',
    $type: 'color',
    $value: 'transparent',
  },
  'color.btn.primary.hover.border': {
    _original: {
      $value: '{color.btn.primary.border}',
    },
    _group: {
      id: 'color.btn.primary.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.primary.hover.border',
    $type: 'color',
    $value: '#0054e5',
  },
  'color.btn.primary.hover.fg': {
    _original: {
      $value: '{color.btn.primary.bg}',
    },
    _group: {
      id: 'color.btn.primary.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.primary.hover.fg',
    $type: 'color',
    $value: '#0054e5',
  },
  'color.btn.secondary.bg': {
    _original: {
      $value: 'transparent',
      $extensions: {
        mode: {
          dark: 'transparent',
        },
      },
    },
    _group: {
      id: 'color.btn.secondary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.secondary.bg',
    $type: 'color',
    $value: 'transparent',
    $extensions: {
      mode: {
        dark: 'transparent',
      },
    },
  },
  'color.btn.secondary.border': {
    _original: {
      $value: '{color.theme.text.primary}',
      $extensions: {
        mode: {
          dark: '{color.gray.600}',
        },
      },
    },
    _group: {
      id: 'color.btn.secondary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.secondary.border',
    $type: 'color',
    $value: '#000000',
    $extensions: {
      mode: {
        dark: '#666666',
      },
    },
  },
  'color.btn.secondary.fg': {
    _original: {
      $value: '{color.theme.text.primary}',
      $extensions: {
        mode: {
          dark: '{color.white}',
        },
      },
    },
    _group: {
      id: 'color.btn.secondary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.secondary.fg',
    $type: 'color',
    $value: '#000000',
    $extensions: {
      mode: {
        dark: '#FFFFFF',
      },
    },
  },
  'color.btn.secondary.hover.bg': {
    _original: {
      $value: '{color.theme.text.primary}',
    },
    _group: {
      id: 'color.btn.secondary.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.secondary.hover.bg',
    $type: 'color',
    $value: '#000000',
  },
  'color.btn.secondary.hover.border': {
    _original: {
      $value: '{color.theme.text.primary}',
    },
    _group: {
      id: 'color.btn.secondary.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.secondary.hover.border',
    $type: 'color',
    $value: '#000000',
  },
  'color.btn.secondary.hover.fg': {
    _original: {
      $value: '{color.white}',
      $extensions: {
        mode: {
          dark: '{color.gray.900}',
        },
      },
    },
    _group: {
      id: 'color.btn.secondary.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.secondary.hover.fg',
    $type: 'color',
    $value: '#FFFFFF',
    $extensions: {
      mode: {
        dark: '#0a0a0a',
      },
    },
  },
  'color.btn.tertiary.bg': {
    _original: {
      $value: '{color.theme.text.primary}',
      $extensions: {
        mode: {
          dark: '{color.gray.100}',
        },
      },
    },
    _group: {
      id: 'color.btn.tertiary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.tertiary.bg',
    $type: 'color',
    $value: '#000000',
    $extensions: {
      mode: {
        dark: '#f5f5f5',
      },
    },
  },
  'color.btn.tertiary.border': {
    _original: {
      $value: '{color.theme.text.primary}',
      $extensions: {
        mode: {
          dark: '{color.gray.100}',
        },
      },
    },
    _group: {
      id: 'color.btn.tertiary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.tertiary.border',
    $type: 'color',
    $value: '#000000',
    $extensions: {
      mode: {
        dark: '#f5f5f5',
      },
    },
  },
  'color.btn.tertiary.fg': {
    _original: {
      $value: '{color.theme.background.default}',
      $extensions: {
        mode: {
          dark: '{color.black}',
        },
      },
    },
    _group: {
      id: 'color.btn.tertiary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.tertiary.fg',
    $type: 'color',
    $value: '#FFFFFF',
    $extensions: {
      mode: {
        dark: '#000000',
      },
    },
  },
  'color.btn.tertiary.hover.bg': {
    _original: {
      $value: '{color.gray.100}',
      $extensions: {
        mode: {
          dark: '{color.gray.900}',
        },
      },
    },
    _group: {
      id: 'color.btn.tertiary.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.tertiary.hover.bg',
    $type: 'color',
    $value: '#f5f5f5',
    $extensions: {
      mode: {
        dark: '#0a0a0a',
      },
    },
  },
  'color.btn.tertiary.hover.border': {
    _original: {
      $value: '{color.btn.tertiary.border}',
    },
    _group: {
      id: 'color.btn.tertiary.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.tertiary.hover.border',
    $type: 'color',
    $value: '#000000',
  },
  'color.btn.tertiary.hover.fg': {
    _original: {
      $value: '{color.theme.text.primary}',
    },
    _group: {
      id: 'color.btn.tertiary.hover',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.tertiary.hover.fg',
    $type: 'color',
    $value: '#000000',
  },
  'color.feedback.error': {
    _original: {
      $value: '#dc3545',
    },
    _group: {
      id: 'color.feedback',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.feedback.error',
    $type: 'color',
    $value: '#dc3545',
  },
  'color.feedback.info': {
    _original: {
      $value: '#17a2b8',
    },
    _group: {
      id: 'color.feedback',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.feedback.info',
    $type: 'color',
    $value: '#17a2b8',
  },
  'color.feedback.success': {
    _original: {
      $value: '#28a745',
    },
    _group: {
      id: 'color.feedback',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.feedback.success',
    $type: 'color',
    $value: '#28a745',
  },
  'color.feedback.warning': {
    _original: {
      $value: '#ffc107',
    },
    _group: {
      id: 'color.feedback',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.feedback.warning',
    $type: 'color',
    $value: '#ffc107',
  },
  'color.gray.100': {
    _original: {
      $value: '#f5f5f5',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.100',
    $type: 'color',
    $value: '#f5f5f5',
  },
  'color.gray.200': {
    _original: {
      $value: '#e5e5e5',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.200',
    $type: 'color',
    $value: '#e5e5e5',
  },
  'color.gray.300': {
    _original: {
      $value: '#b8b8b8',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.300',
    $type: 'color',
    $value: '#b8b8b8',
  },
  'color.gray.400': {
    _original: {
      $value: '#999999',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.400',
    $type: 'color',
    $value: '#999999',
  },
  'color.gray.500': {
    _original: {
      $value: '#888888',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.500',
    $type: 'color',
    $value: '#888888',
  },
  'color.gray.600': {
    _original: {
      $value: '#666666',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.600',
    $type: 'color',
    $value: '#666666',
  },
  'color.gray.700': {
    _original: {
      $value: '#333333',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.700',
    $type: 'color',
    $value: '#333333',
  },
  'color.gray.800': {
    _original: {
      $value: '#1a1a1a',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.800',
    $type: 'color',
    $value: '#1a1a1a',
  },
  'color.gray.900': {
    _original: {
      $value: '#0a0a0a',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.900',
    $type: 'color',
    $value: '#0a0a0a',
  },
  'color.theme.background.default': {
    _original: {
      $value: '{color.white}',
      $extensions: {
        mode: {
          dark: '{color.gray.900}',
        },
      },
    },
    _group: {
      id: 'color.theme.background',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.background.default',
    $type: 'color',
    $value: '#FFFFFF',
    $extensions: {
      mode: {
        dark: '#0a0a0a',
      },
    },
  },
  'color.theme.background.surface': {
    _original: {
      $value: '{color.gray.100}',
      $extensions: {
        mode: {
          dark: '{color.gray.800}',
        },
      },
    },
    _group: {
      id: 'color.theme.background',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.background.surface',
    $type: 'color',
    $value: '#f5f5f5',
    $extensions: {
      mode: {
        dark: '#1a1a1a',
      },
    },
  },
  'color.theme.border.default': {
    _original: {
      $value: '{color.gray.600}',
      $extensions: {
        mode: {
          dark: '{color.gray.600}',
        },
      },
    },
    _group: {
      id: 'color.theme.border',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.border.default',
    $type: 'color',
    $value: '#666666',
    $extensions: {
      mode: {
        dark: '#666666',
      },
    },
  },
  'color.theme.border.light': {
    _original: {
      $value: '{color.gray.100}',
      $extensions: {
        mode: {
          dark: '{color.gray.100}',
        },
      },
    },
    _group: {
      id: 'color.theme.border',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.border.light',
    $type: 'color',
    $value: '#f5f5f5',
    $extensions: {
      mode: {
        dark: '#f5f5f5',
      },
    },
  },
  'color.theme.state.disabled': {
    _original: {
      $value: '{color.gray.300}',
    },
    _group: {
      id: 'color.theme.state',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.state.disabled',
    $type: 'color',
    $value: '#b8b8b8',
  },
  'color.theme.state.focus': {
    _original: {
      $value: '{color.brand.interactive}',
    },
    _group: {
      id: 'color.theme.state',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.state.focus',
    $type: 'color',
    $value: '#0054e5',
  },
  'color.theme.status.error-text': {
    _original: {
      $value: '{color.feedback.error}',
    },
    _group: {
      id: 'color.theme.status',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.status.error-text',
    $type: 'color',
    $value: '#dc3545',
  },
  'color.theme.status.success-bg': {
    _original: {
      $value: '#d4edda',
      $extensions: {
        mode: {
          dark: '#1b5e20',
        },
      },
    },
    _group: {
      id: 'color.theme.status',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.status.success-bg',
    $type: 'color',
    $value: '#d4edda',
    $extensions: {
      mode: {
        dark: '#1b5e20',
      },
    },
  },
  'color.theme.text.muted': {
    _original: {
      $value: '{color.gray.600}',
      $extensions: {
        mode: {
          dark: '{color.gray.500}',
        },
      },
    },
    _group: {
      id: 'color.theme.text',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.text.muted',
    $type: 'color',
    $value: '#666666',
    $extensions: {
      mode: {
        dark: '#888888',
      },
    },
  },
  'color.theme.text.primary': {
    _original: {
      $value: '{color.black}',
      $extensions: {
        mode: {
          dark: '{color.gray.100}',
        },
      },
    },
    _group: {
      id: 'color.theme.text',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.text.primary',
    $type: 'color',
    $value: '#000000',
    $extensions: {
      mode: {
        dark: '#f5f5f5',
      },
    },
  },
  'color.theme.text.secondary': {
    _original: {
      $value: '{color.gray.700}',
      $extensions: {
        mode: {
          dark: '{color.gray.300}',
        },
      },
    },
    _group: {
      id: 'color.theme.text',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.theme.text.secondary',
    $type: 'color',
    $value: '#333333',
    $extensions: {
      mode: {
        dark: '#b8b8b8',
      },
    },
  },
  'color.white': {
    _original: {
      $value: '#FFFFFF',
    },
    _group: {
      id: 'color',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.white',
    $type: 'color',
    $value: '#FFFFFF',
  },
  'max-width.default': {
    _original: {
      $value: '75rem',
      $extensions: {
        mode: {
          zoomed: '125rem',
        },
      },
    },
    _group: {
      id: 'max-width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'max-width.default',
    $type: 'dimension',
    $value: '75rem',
    $extensions: {
      mode: {
        zoomed: '125rem',
      },
    },
  },
  'max-width.medium': {
    _original: {
      $value: '50rem',
    },
    _group: {
      id: 'max-width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'max-width.medium',
    $type: 'dimension',
    $value: '50rem',
  },
  'max-width.narrow': {
    _original: {
      $value: '20rem',
    },
    _group: {
      id: 'max-width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'max-width.narrow',
    $type: 'dimension',
    $value: '20rem',
  },
  'max-width.thin': {
    _original: {
      $value: '37.5rem',
      $extensions: {
        mode: {
          zoomed: '62.5rem',
        },
      },
    },
    _group: {
      id: 'max-width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'max-width.thin',
    $type: 'dimension',
    $value: '37.5rem',
    $extensions: {
      mode: {
        zoomed: '62.5rem',
      },
    },
  },
  'space.lg': {
    _original: {
      $value: '2rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.lg',
    $type: 'dimension',
    $value: '2rem',
  },
  'space.md': {
    _original: {
      $value: '1.5rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.md',
    $type: 'dimension',
    $value: '1.5rem',
  },
  'space.semantic.padding': {
    _original: {
      $value: '{space.sm}',
    },
    _group: {
      id: 'space.semantic',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.semantic.padding',
    $type: 'dimension',
    $value: '1rem',
  },
  'space.sm': {
    _original: {
      $value: '1rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.sm',
    $type: 'dimension',
    $value: '1rem',
  },
  'space.xl': {
    _original: {
      $value: '3rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xl',
    $type: 'dimension',
    $value: '3rem',
  },
  'space.xs': {
    _original: {
      $value: '0.75rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xs',
    $type: 'dimension',
    $value: '0.75rem',
  },
  'space.xxl': {
    _original: {
      $value: '4rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xxl',
    $type: 'dimension',
    $value: '4rem',
  },
  'space.xxs': {
    _original: {
      $value: '0.5rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xxs',
    $type: 'dimension',
    $value: '0.5rem',
  },
  'space.xxxl': {
    _original: {
      $value: '5rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xxxl',
    $type: 'dimension',
    $value: '5rem',
  },
  'space.xxxs': {
    _original: {
      $value: '0.25rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xxxs',
    $type: 'dimension',
    $value: '0.25rem',
  },
  'transition.duration.fast': {
    _original: {
      $value: '0.1s',
      $extensions: {
        mode: {
          reducedMotion: '0s',
        },
      },
    },
    _group: {
      id: 'transition.duration',
      $extensions: {
        requiredModes: [],
      },
      $type: 'duration',
    },
    id: 'transition.duration.fast',
    $type: 'duration',
    $value: '0.1s',
    $extensions: {
      mode: {
        reducedMotion: '0ms',
      },
    },
  },
  'transition.duration.normal': {
    _original: {
      $value: '0.2s',
      $extensions: {
        mode: {
          reducedMotion: '0s',
        },
      },
    },
    _group: {
      id: 'transition.duration',
      $extensions: {
        requiredModes: [],
      },
      $type: 'duration',
    },
    id: 'transition.duration.normal',
    $type: 'duration',
    $value: '0.2s',
    $extensions: {
      mode: {
        reducedMotion: '0ms',
      },
    },
  },
  'transition.duration.slow': {
    _original: {
      $value: '0.3s',
      $extensions: {
        mode: {
          reducedMotion: '0s',
        },
      },
    },
    _group: {
      id: 'transition.duration',
      $extensions: {
        requiredModes: [],
      },
      $type: 'duration',
    },
    id: 'transition.duration.slow',
    $type: 'duration',
    $value: '0.3s',
    $extensions: {
      mode: {
        reducedMotion: '0ms',
      },
    },
  },
  'typography.font-family.body': {
    _original: {
      $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
    },
    _group: {
      id: 'typography.font-family',
      $extensions: {
        requiredModes: [],
      },
      $type: 'fontFamily',
    },
    id: 'typography.font-family.body',
    $type: 'fontFamily',
    $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  },
  'typography.font-family.mono': {
    _original: {
      $value: 'monospace',
    },
    _group: {
      id: 'typography.font-family',
      $extensions: {
        requiredModes: [],
      },
      $type: 'fontFamily',
    },
    id: 'typography.font-family.mono',
    $type: 'fontFamily',
    $value: ['monospace'],
  },
  'typography.font-family.primary': {
    _original: {
      $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
    },
    _group: {
      id: 'typography.font-family',
      $extensions: {
        requiredModes: [],
      },
      $type: 'fontFamily',
    },
    id: 'typography.font-family.primary',
    $type: 'fontFamily',
    $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  },
  'typography.font-family.secondary': {
    _original: {
      $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
    },
    _group: {
      id: 'typography.font-family',
      $extensions: {
        requiredModes: [],
      },
      $type: 'fontFamily',
    },
    id: 'typography.font-family.secondary',
    $type: 'fontFamily',
    $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  },
  'typography.font-size.btn.default': {
    _original: {
      $value: 'calc(1.15rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.btn',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.btn.default',
    $type: 'dimension',
    $value: 'calc(1.15rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.btn.sm': {
    _original: {
      $value: 'calc(1rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.btn',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.btn.sm',
    $type: 'dimension',
    $value: 'calc(1rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.1': {
    _original: {
      $value: 'calc(clamp(2rem, 4vw + 1rem, 3.5rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.1',
    $type: 'dimension',
    $value: 'calc(clamp(2rem, 4vw + 1rem, 3.5rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.2': {
    _original: {
      $value: 'calc(clamp(1.5rem, 3vw + 1rem, 3rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.2',
    $type: 'dimension',
    $value: 'calc(clamp(1.5rem, 3vw + 1rem, 3rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.3': {
    _original: {
      $value: 'calc(clamp(1.3rem, 2.5vw + 1rem, 2.5rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.3',
    $type: 'dimension',
    $value: 'calc(clamp(1.3rem, 2.5vw + 1rem, 2.5rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.4': {
    _original: {
      $value: 'calc(clamp(1.2rem, 2.5vw + 1rem, 2rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.4',
    $type: 'dimension',
    $value: 'calc(clamp(1.2rem, 2.5vw + 1rem, 2rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.5': {
    _original: {
      $value: 'calc(clamp(1.15rem, 2vw + 1rem, 1.4rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.5',
    $type: 'dimension',
    $value: 'calc(clamp(1.15rem, 2vw + 1rem, 1.4rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.6': {
    _original: {
      $value: 'calc(clamp(1.125rem, 1.8vw + 1rem, 1.25rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.6',
    $type: 'dimension',
    $value: 'calc(clamp(1.125rem, 1.8vw + 1rem, 1.25rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.1': {
    _original: {
      $value: 'calc(1.1rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.1',
    $type: 'dimension',
    $value: 'calc(1.1rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.2': {
    _original: {
      $value: 'calc(1rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.2',
    $type: 'dimension',
    $value: 'calc(1rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.3': {
    _original: {
      $value: 'calc(0.95rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.3',
    $type: 'dimension',
    $value: 'calc(0.95rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.4': {
    _original: {
      $value: 'calc(0.9rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.4',
    $type: 'dimension',
    $value: 'calc(0.9rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.5': {
    _original: {
      $value: 'calc(0.85rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.5',
    $type: 'dimension',
    $value: 'calc(0.85rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.scale': {
    _original: {
      $type: 'number',
      $value: 1,
      $extensions: {
        mode: {
          zoomed: 1.15,
        },
      },
    },
    _group: {
      id: 'typography.font-size',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.scale',
    $type: 'number',
    $value: 1,
    $extensions: {
      mode: {
        zoomed: 1.15,
      },
    },
  },
  'typography.font-weight.bold': {
    _original: {
      $value: 700,
    },
    _group: {
      id: 'typography.font-weight',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.font-weight.bold',
    $type: 'number',
    $value: 700,
  },
  'typography.font-weight.bolder': {
    _original: {
      $value: 900,
    },
    _group: {
      id: 'typography.font-weight',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.font-weight.bolder',
    $type: 'number',
    $value: 900,
  },
  'typography.font-weight.lighter': {
    _original: {
      $value: 300,
    },
    _group: {
      id: 'typography.font-weight',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.font-weight.lighter',
    $type: 'number',
    $value: 300,
  },
  'typography.font-weight.normal': {
    _original: {
      $value: 400,
    },
    _group: {
      id: 'typography.font-weight',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.font-weight.normal',
    $type: 'number',
    $value: 400,
  },
  'typography.letter-spacing.lg': {
    _original: {
      $value: '0.05rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.lg',
    $type: 'dimension',
    $value: '0.05rem',
  },
  'typography.letter-spacing.md': {
    _original: {
      $value: '0.03rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.md',
    $type: 'dimension',
    $value: '0.03rem',
  },
  'typography.letter-spacing.sm': {
    _original: {
      $value: '0.02rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.sm',
    $type: 'dimension',
    $value: '0.02rem',
  },
  'typography.letter-spacing.xl': {
    _original: {
      $value: '0.08rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.xl',
    $type: 'dimension',
    $value: '0.08rem',
  },
  'typography.letter-spacing.xs': {
    _original: {
      $value: '0.01rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.xs',
    $type: 'dimension',
    $value: '0.01rem',
  },
  'typography.letter-spacing.xxl': {
    _original: {
      $value: '0.1rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.xxl',
    $type: 'dimension',
    $value: '0.1rem',
  },
  'typography.line-height.lg': {
    _original: {
      $value: 1.6,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.lg',
    $type: 'number',
    $value: 1.6,
  },
  'typography.line-height.md': {
    _original: {
      $value: 1.3,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.md',
    $type: 'number',
    $value: 1.3,
  },
  'typography.line-height.sm': {
    _original: {
      $value: 1.1,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.sm',
    $type: 'number',
    $value: 1.1,
  },
  'typography.line-height.xl': {
    _original: {
      $value: 1.7,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.xl',
    $type: 'number',
    $value: 1.7,
  },
  'typography.line-height.xs': {
    _original: {
      $value: 1,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.xs',
    $type: 'number',
    $value: 1,
  },
};

export const modes = {
  'color.btn.primary.bg': {
    dark: '#0054e5',
  },
  'color.btn.primary.border': {
    dark: '#0054e5',
  },
  'color.btn.primary.fg': {
    dark: '#FFFFFF',
  },
  'color.btn.secondary.bg': {
    dark: 'transparent',
  },
  'color.btn.secondary.border': {
    dark: '#666666',
  },
  'color.btn.secondary.fg': {
    dark: '#FFFFFF',
  },
  'color.btn.secondary.hover.fg': {
    dark: '#0a0a0a',
  },
  'color.btn.tertiary.bg': {
    dark: '#f5f5f5',
  },
  'color.btn.tertiary.border': {
    dark: '#f5f5f5',
  },
  'color.btn.tertiary.fg': {
    dark: '#000000',
  },
  'color.btn.tertiary.hover.bg': {
    dark: '#0a0a0a',
  },
  'color.theme.background.default': {
    dark: '#0a0a0a',
  },
  'color.theme.background.surface': {
    dark: '#1a1a1a',
  },
  'color.theme.border.default': {
    dark: '#666666',
  },
  'color.theme.border.light': {
    dark: '#f5f5f5',
  },
  'color.theme.status.success-bg': {
    dark: '#1b5e20',
  },
  'color.theme.text.muted': {
    dark: '#888888',
  },
  'color.theme.text.primary': {
    dark: '#f5f5f5',
  },
  'color.theme.text.secondary': {
    dark: '#b8b8b8',
  },
  'max-width.default': {
    zoomed: '125rem',
  },
  'max-width.thin': {
    zoomed: '62.5rem',
  },
  'transition.duration.fast': {
    reducedMotion: '0ms',
  },
  'transition.duration.normal': {
    reducedMotion: '0ms',
  },
  'transition.duration.slow': {
    reducedMotion: '0ms',
  },
  'typography.font-size.scale': {
    zoomed: 1.15,
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
