/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

export const tokens = {
  'border.radius.lg': '8px',
  'border.radius.md': '4px',
  'border.radius.sm': '2px',
  'border.width.lg': '4px',
  'border.width.md': '2px',
  'border.width.sm': '1px',
  'color.accent': '#a20000',
  'color.background': 'white',
  'color.black': 'black',
  'color.border': '#666',
  'color.btn.primary.bg': '#0054e5',
  'color.btn.primary.border': '#0054e5',
  'color.btn.primary.fg': 'white',
  'color.btn.secondary.bg': 'transparent',
  'color.btn.secondary.border': '#666',
  'color.btn.secondary.fg': 'black',
  'color.btn.tertiary.bg': 'black',
  'color.btn.tertiary.border': 'white',
  'color.btn.tertiary.fg': 'white',
  'color.gray.dark': '#333',
  'color.gray.light': '#f5f5f5',
  'color.gray.medium': '#666',
  'color.interaction.default': '#0054e5',
  'color.surface': '#f5f5f5',
  'color.text.muted': '#666',
  'color.text.primary': 'black',
  'color.text.secondary': '#333',
  'color.white': 'white',
  'max-width.default': '75rem',
  'max-width.medium': '50rem',
  'max-width.narrow': '20rem',
  'max-width.thin': '37.5rem',
  'space.lg': '2rem',
  'space.md': '1.5rem',
  'space.semantic.padding': '1rem',
  'space.sm': '1rem',
  'space.xl': '3rem',
  'space.xs': '0.75rem',
  'space.xxl': '4rem',
  'space.xxs': '0.5rem',
  'space.xxxl': '5rem',
  'space.xxxs': '0.25rem',
  'transition.duration.fast': '0.1s',
  'transition.duration.normal': '0.2s',
  'transition.duration.slow': '0.3s',
  'typography.font-family.body': ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  'typography.font-family.mono': ['monospace'],
  'typography.font-family.primary': ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  'typography.font-family.secondary': ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  'typography.font-size.btn.default': 'calc(1.15rem * var(--typography-font-size-scale))',
  'typography.font-size.btn.sm': 'calc(1rem * var(--typography-font-size-scale))',
  'typography.font-size.heading.1': 'calc(clamp(2rem, 4vw + 1rem, 3.5rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.2': 'calc(clamp(1.5rem, 3vw + 1rem, 3rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.3': 'calc(clamp(1.3rem, 2.5vw + 1rem, 2.5rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.4': 'calc(clamp(1.2rem, 2.5vw + 1rem, 2rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.5': 'calc(clamp(1.15rem, 2vw + 1rem, 1.4rem) * var(--typography-font-size-scale))',
  'typography.font-size.heading.6': 'calc(clamp(1.125rem, 1.8vw + 1rem, 1.25rem) * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.1': 'calc(1.1rem * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.2': 'calc(1rem * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.3': 'calc(0.95rem * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.4': 'calc(0.9rem * var(--typography-font-size-scale))',
  'typography.font-size.paragraph.5': 'calc(0.85rem * var(--typography-font-size-scale))',
  'typography.font-size.scale': 1,
  'typography.font-weight.bold': 700,
  'typography.font-weight.bolder': 900,
  'typography.font-weight.lighter': 300,
  'typography.font-weight.normal': 400,
  'typography.letter-spacing.lg': '0.05rem',
  'typography.letter-spacing.md': '0.03rem',
  'typography.letter-spacing.sm': '0.02rem',
  'typography.letter-spacing.xl': '0.08rem',
  'typography.letter-spacing.xs': '0.01rem',
  'typography.letter-spacing.xxl': '0.1rem',
  'typography.line-height.lg': 1.6,
  'typography.line-height.md': 1.3,
  'typography.line-height.sm': 1.1,
  'typography.line-height.xl': 1.7,
  'typography.line-height.xs': 1,
};

export const meta = {
  'border.radius.lg': {
    _original: {
      $value: '8px',
    },
    _group: {
      id: 'border.radius',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.radius.lg',
    $type: 'dimension',
    $value: '8px',
  },
  'border.radius.md': {
    _original: {
      $value: '4px',
    },
    _group: {
      id: 'border.radius',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.radius.md',
    $type: 'dimension',
    $value: '4px',
  },
  'border.radius.sm': {
    _original: {
      $value: '2px',
    },
    _group: {
      id: 'border.radius',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.radius.sm',
    $type: 'dimension',
    $value: '2px',
  },
  'border.width.lg': {
    _original: {
      $value: '4px',
    },
    _group: {
      id: 'border.width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.width.lg',
    $type: 'dimension',
    $value: '4px',
  },
  'border.width.md': {
    _original: {
      $value: '2px',
    },
    _group: {
      id: 'border.width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.width.md',
    $type: 'dimension',
    $value: '2px',
  },
  'border.width.sm': {
    _original: {
      $value: '1px',
    },
    _group: {
      id: 'border.width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'border.width.sm',
    $type: 'dimension',
    $value: '1px',
  },
  'color.accent': {
    _original: {
      $value: '#a20000',
      $extensions: {
        mode: {
          dark: '#ff3333',
        },
      },
    },
    _group: {
      id: 'color',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.accent',
    $type: 'color',
    $value: '#a20000',
    $extensions: {
      mode: {
        dark: '#ff3333',
      },
    },
  },
  'color.background': {
    _original: {
      $value: '{color.white}',
      $extensions: {
        mode: {
          dark: '#0a0a0a',
        },
      },
    },
    _group: {
      id: 'color',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.background',
    $type: 'color',
    $value: 'white',
    $extensions: {
      mode: {
        dark: '#0a0a0a',
      },
    },
  },
  'color.black': {
    _original: {
      $value: 'black',
    },
    _group: {
      id: 'color',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.black',
    $type: 'color',
    $value: 'black',
  },
  'color.border': {
    _original: {
      $value: '{color.gray.medium}',
    },
    _group: {
      id: 'color',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.border',
    $type: 'color',
    $value: '#666',
  },
  'color.btn.primary.bg': {
    _original: {
      $value: '{color.interaction.default}',
      $extensions: {
        mode: {
          dark: '{color.interaction.default}',
        },
      },
    },
    _group: {
      id: 'color.btn.primary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.primary.bg',
    $type: 'color',
    $value: '#0054e5',
    $extensions: {
      mode: {
        dark: '#0054e5',
      },
    },
  },
  'color.btn.primary.border': {
    _original: {
      $value: '{color.btn.primary.bg}',
      $extensions: {
        mode: {
          dark: '{color.interaction.default}',
        },
      },
    },
    _group: {
      id: 'color.btn.primary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.primary.border',
    $type: 'color',
    $value: '#0054e5',
    $extensions: {
      mode: {
        dark: '#0054e5',
      },
    },
  },
  'color.btn.primary.fg': {
    _original: {
      $value: '{color.white}',
      $extensions: {
        mode: {
          dark: '{color.white}',
        },
      },
    },
    _group: {
      id: 'color.btn.primary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.primary.fg',
    $type: 'color',
    $value: 'white',
    $extensions: {
      mode: {
        dark: 'white',
      },
    },
  },
  'color.btn.secondary.bg': {
    _original: {
      $value: 'transparent',
      $extensions: {
        mode: {
          dark: 'transparent',
        },
      },
    },
    _group: {
      id: 'color.btn.secondary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.secondary.bg',
    $type: 'color',
    $value: 'transparent',
    $extensions: {
      mode: {
        dark: 'transparent',
      },
    },
  },
  'color.btn.secondary.border': {
    _original: {
      $value: '{color.gray.medium}',
      $extensions: {
        mode: {
          dark: '{color.gray.medium}',
        },
      },
    },
    _group: {
      id: 'color.btn.secondary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.secondary.border',
    $type: 'color',
    $value: '#666',
    $extensions: {
      mode: {
        dark: '#666',
      },
    },
  },
  'color.btn.secondary.fg': {
    _original: {
      $value: '{color.black}',
      $extensions: {
        mode: {
          dark: '{color.white}',
        },
      },
    },
    _group: {
      id: 'color.btn.secondary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.secondary.fg',
    $type: 'color',
    $value: 'black',
    $extensions: {
      mode: {
        dark: 'white',
      },
    },
  },
  'color.btn.tertiary.bg': {
    _original: {
      $value: '{color.black}',
      $extensions: {
        mode: {
          dark: '{color.gray.light}',
        },
      },
    },
    _group: {
      id: 'color.btn.tertiary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.tertiary.bg',
    $type: 'color',
    $value: 'black',
    $extensions: {
      mode: {
        dark: '#f5f5f5',
      },
    },
  },
  'color.btn.tertiary.border': {
    _original: {
      $value: '{color.white}',
      $extensions: {
        mode: {
          dark: '{color.gray.medium}',
        },
      },
    },
    _group: {
      id: 'color.btn.tertiary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.tertiary.border',
    $type: 'color',
    $value: 'white',
    $extensions: {
      mode: {
        dark: '#666',
      },
    },
  },
  'color.btn.tertiary.fg': {
    _original: {
      $value: '{color.white}',
      $extensions: {
        mode: {
          dark: '{color.black}',
        },
      },
    },
    _group: {
      id: 'color.btn.tertiary',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.btn.tertiary.fg',
    $type: 'color',
    $value: 'white',
    $extensions: {
      mode: {
        dark: 'black',
      },
    },
  },
  'color.gray.dark': {
    _original: {
      $value: '#333',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.dark',
    $type: 'color',
    $value: '#333',
  },
  'color.gray.light': {
    _original: {
      $value: '#f5f5f5',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.light',
    $type: 'color',
    $value: '#f5f5f5',
  },
  'color.gray.medium': {
    _original: {
      $value: '#666',
    },
    _group: {
      id: 'color.gray',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.gray.medium',
    $type: 'color',
    $value: '#666',
  },
  'color.interaction.default': {
    _original: {
      $value: '#0054e5',
    },
    _group: {
      id: 'color.interaction',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.interaction.default',
    $type: 'color',
    $value: '#0054e5',
  },
  'color.surface': {
    _original: {
      $value: '{color.gray.light}',
      $extensions: {
        mode: {
          dark: '#1a1a1a',
        },
      },
    },
    _group: {
      id: 'color',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.surface',
    $type: 'color',
    $value: '#f5f5f5',
    $extensions: {
      mode: {
        dark: '#1a1a1a',
      },
    },
  },
  'color.text.muted': {
    _original: {
      $value: '{color.gray.medium}',
      $extensions: {
        mode: {
          dark: '#888888',
        },
      },
    },
    _group: {
      id: 'color.text',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.text.muted',
    $type: 'color',
    $value: '#666',
    $extensions: {
      mode: {
        dark: '#888888',
      },
    },
  },
  'color.text.primary': {
    _original: {
      $value: '{color.black}',
      $extensions: {
        mode: {
          dark: '#f5f5f5',
        },
      },
    },
    _group: {
      id: 'color.text',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.text.primary',
    $type: 'color',
    $value: 'black',
    $extensions: {
      mode: {
        dark: '#f5f5f5',
      },
    },
  },
  'color.text.secondary': {
    _original: {
      $value: '{color.gray.dark}',
      $extensions: {
        mode: {
          dark: '#b8b8b8',
        },
      },
    },
    _group: {
      id: 'color.text',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.text.secondary',
    $type: 'color',
    $value: '#333',
    $extensions: {
      mode: {
        dark: '#b8b8b8',
      },
    },
  },
  'color.white': {
    _original: {
      $value: 'white',
    },
    _group: {
      id: 'color',
      $extensions: {
        requiredModes: [],
      },
      $type: 'color',
    },
    id: 'color.white',
    $type: 'color',
    $value: 'white',
  },
  'max-width.default': {
    _original: {
      $value: '75rem',
      $extensions: {
        mode: {
          zoomed: '125rem',
        },
      },
    },
    _group: {
      id: 'max-width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'max-width.default',
    $type: 'dimension',
    $value: '75rem',
    $extensions: {
      mode: {
        zoomed: '125rem',
      },
    },
  },
  'max-width.medium': {
    _original: {
      $value: '50rem',
    },
    _group: {
      id: 'max-width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'max-width.medium',
    $type: 'dimension',
    $value: '50rem',
  },
  'max-width.narrow': {
    _original: {
      $value: '20rem',
    },
    _group: {
      id: 'max-width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'max-width.narrow',
    $type: 'dimension',
    $value: '20rem',
  },
  'max-width.thin': {
    _original: {
      $value: '37.5rem',
      $extensions: {
        mode: {
          zoomed: '62.5rem',
        },
      },
    },
    _group: {
      id: 'max-width',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'max-width.thin',
    $type: 'dimension',
    $value: '37.5rem',
    $extensions: {
      mode: {
        zoomed: '62.5rem',
      },
    },
  },
  'space.lg': {
    _original: {
      $value: '2rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.lg',
    $type: 'dimension',
    $value: '2rem',
  },
  'space.md': {
    _original: {
      $value: '1.5rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.md',
    $type: 'dimension',
    $value: '1.5rem',
  },
  'space.semantic.padding': {
    _original: {
      $value: '{space.sm}',
    },
    _group: {
      id: 'space.semantic',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.semantic.padding',
    $type: 'dimension',
    $value: '1rem',
  },
  'space.sm': {
    _original: {
      $value: '1rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.sm',
    $type: 'dimension',
    $value: '1rem',
  },
  'space.xl': {
    _original: {
      $value: '3rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xl',
    $type: 'dimension',
    $value: '3rem',
  },
  'space.xs': {
    _original: {
      $value: '0.75rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xs',
    $type: 'dimension',
    $value: '0.75rem',
  },
  'space.xxl': {
    _original: {
      $value: '4rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xxl',
    $type: 'dimension',
    $value: '4rem',
  },
  'space.xxs': {
    _original: {
      $value: '0.5rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xxs',
    $type: 'dimension',
    $value: '0.5rem',
  },
  'space.xxxl': {
    _original: {
      $value: '5rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xxxl',
    $type: 'dimension',
    $value: '5rem',
  },
  'space.xxxs': {
    _original: {
      $value: '0.25rem',
    },
    _group: {
      id: 'space',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'space.xxxs',
    $type: 'dimension',
    $value: '0.25rem',
  },
  'transition.duration.fast': {
    _original: {
      $value: '0.1s',
      $extensions: {
        mode: {
          reducedMotion: '0s',
        },
      },
    },
    _group: {
      id: 'transition.duration',
      $extensions: {
        requiredModes: [],
      },
      $type: 'duration',
    },
    id: 'transition.duration.fast',
    $type: 'duration',
    $value: '0.1s',
    $extensions: {
      mode: {
        reducedMotion: '0ms',
      },
    },
  },
  'transition.duration.normal': {
    _original: {
      $value: '0.2s',
      $extensions: {
        mode: {
          reducedMotion: '0s',
        },
      },
    },
    _group: {
      id: 'transition.duration',
      $extensions: {
        requiredModes: [],
      },
      $type: 'duration',
    },
    id: 'transition.duration.normal',
    $type: 'duration',
    $value: '0.2s',
    $extensions: {
      mode: {
        reducedMotion: '0ms',
      },
    },
  },
  'transition.duration.slow': {
    _original: {
      $value: '0.3s',
      $extensions: {
        mode: {
          reducedMotion: '0s',
        },
      },
    },
    _group: {
      id: 'transition.duration',
      $extensions: {
        requiredModes: [],
      },
      $type: 'duration',
    },
    id: 'transition.duration.slow',
    $type: 'duration',
    $value: '0.3s',
    $extensions: {
      mode: {
        reducedMotion: '0ms',
      },
    },
  },
  'typography.font-family.body': {
    _original: {
      $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
    },
    _group: {
      id: 'typography.font-family',
      $extensions: {
        requiredModes: [],
      },
      $type: 'fontFamily',
    },
    id: 'typography.font-family.body',
    $type: 'fontFamily',
    $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  },
  'typography.font-family.mono': {
    _original: {
      $value: 'monospace',
    },
    _group: {
      id: 'typography.font-family',
      $extensions: {
        requiredModes: [],
      },
      $type: 'fontFamily',
    },
    id: 'typography.font-family.mono',
    $type: 'fontFamily',
    $value: ['monospace'],
  },
  'typography.font-family.primary': {
    _original: {
      $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
    },
    _group: {
      id: 'typography.font-family',
      $extensions: {
        requiredModes: [],
      },
      $type: 'fontFamily',
    },
    id: 'typography.font-family.primary',
    $type: 'fontFamily',
    $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  },
  'typography.font-family.secondary': {
    _original: {
      $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
    },
    _group: {
      id: 'typography.font-family',
      $extensions: {
        requiredModes: [],
      },
      $type: 'fontFamily',
    },
    id: 'typography.font-family.secondary',
    $type: 'fontFamily',
    $value: ['AtkinsonHyperlegible', '-system-ui', 'sans-serif'],
  },
  'typography.font-size.btn.default': {
    _original: {
      $value: 'calc(1.15rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.btn',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.btn.default',
    $type: 'dimension',
    $value: 'calc(1.15rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.btn.sm': {
    _original: {
      $value: 'calc(1rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.btn',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.btn.sm',
    $type: 'dimension',
    $value: 'calc(1rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.1': {
    _original: {
      $value: 'calc(clamp(2rem, 4vw + 1rem, 3.5rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.1',
    $type: 'dimension',
    $value: 'calc(clamp(2rem, 4vw + 1rem, 3.5rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.2': {
    _original: {
      $value: 'calc(clamp(1.5rem, 3vw + 1rem, 3rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.2',
    $type: 'dimension',
    $value: 'calc(clamp(1.5rem, 3vw + 1rem, 3rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.3': {
    _original: {
      $value: 'calc(clamp(1.3rem, 2.5vw + 1rem, 2.5rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.3',
    $type: 'dimension',
    $value: 'calc(clamp(1.3rem, 2.5vw + 1rem, 2.5rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.4': {
    _original: {
      $value: 'calc(clamp(1.2rem, 2.5vw + 1rem, 2rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.4',
    $type: 'dimension',
    $value: 'calc(clamp(1.2rem, 2.5vw + 1rem, 2rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.5': {
    _original: {
      $value: 'calc(clamp(1.15rem, 2vw + 1rem, 1.4rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.5',
    $type: 'dimension',
    $value: 'calc(clamp(1.15rem, 2vw + 1rem, 1.4rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.heading.6': {
    _original: {
      $value: 'calc(clamp(1.125rem, 1.8vw + 1rem, 1.25rem) * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.heading',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.heading.6',
    $type: 'dimension',
    $value: 'calc(clamp(1.125rem, 1.8vw + 1rem, 1.25rem) * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.1': {
    _original: {
      $value: 'calc(1.1rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.1',
    $type: 'dimension',
    $value: 'calc(1.1rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.2': {
    _original: {
      $value: 'calc(1rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.2',
    $type: 'dimension',
    $value: 'calc(1rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.3': {
    _original: {
      $value: 'calc(0.95rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.3',
    $type: 'dimension',
    $value: 'calc(0.95rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.4': {
    _original: {
      $value: 'calc(0.9rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.4',
    $type: 'dimension',
    $value: 'calc(0.9rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.paragraph.5': {
    _original: {
      $value: 'calc(0.85rem * var(--typography-font-size-scale))',
    },
    _group: {
      id: 'typography.font-size.paragraph',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.paragraph.5',
    $type: 'dimension',
    $value: 'calc(0.85rem * var(--typography-font-size-scale))',
  },
  'typography.font-size.scale': {
    _original: {
      $type: 'number',
      $value: 1,
      $extensions: {
        mode: {
          zoomed: 1.15,
        },
      },
    },
    _group: {
      id: 'typography.font-size',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.font-size.scale',
    $type: 'number',
    $value: 1,
    $extensions: {
      mode: {
        zoomed: 1.15,
      },
    },
  },
  'typography.font-weight.bold': {
    _original: {
      $value: 700,
    },
    _group: {
      id: 'typography.font-weight',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.font-weight.bold',
    $type: 'number',
    $value: 700,
  },
  'typography.font-weight.bolder': {
    _original: {
      $value: 900,
    },
    _group: {
      id: 'typography.font-weight',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.font-weight.bolder',
    $type: 'number',
    $value: 900,
  },
  'typography.font-weight.lighter': {
    _original: {
      $value: 300,
    },
    _group: {
      id: 'typography.font-weight',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.font-weight.lighter',
    $type: 'number',
    $value: 300,
  },
  'typography.font-weight.normal': {
    _original: {
      $value: 400,
    },
    _group: {
      id: 'typography.font-weight',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.font-weight.normal',
    $type: 'number',
    $value: 400,
  },
  'typography.letter-spacing.lg': {
    _original: {
      $value: '0.05rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.lg',
    $type: 'dimension',
    $value: '0.05rem',
  },
  'typography.letter-spacing.md': {
    _original: {
      $value: '0.03rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.md',
    $type: 'dimension',
    $value: '0.03rem',
  },
  'typography.letter-spacing.sm': {
    _original: {
      $value: '0.02rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.sm',
    $type: 'dimension',
    $value: '0.02rem',
  },
  'typography.letter-spacing.xl': {
    _original: {
      $value: '0.08rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.xl',
    $type: 'dimension',
    $value: '0.08rem',
  },
  'typography.letter-spacing.xs': {
    _original: {
      $value: '0.01rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.xs',
    $type: 'dimension',
    $value: '0.01rem',
  },
  'typography.letter-spacing.xxl': {
    _original: {
      $value: '0.1rem',
    },
    _group: {
      id: 'typography.letter-spacing',
      $extensions: {
        requiredModes: [],
      },
      $type: 'dimension',
    },
    id: 'typography.letter-spacing.xxl',
    $type: 'dimension',
    $value: '0.1rem',
  },
  'typography.line-height.lg': {
    _original: {
      $value: 1.6,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.lg',
    $type: 'number',
    $value: 1.6,
  },
  'typography.line-height.md': {
    _original: {
      $value: 1.3,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.md',
    $type: 'number',
    $value: 1.3,
  },
  'typography.line-height.sm': {
    _original: {
      $value: 1.1,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.sm',
    $type: 'number',
    $value: 1.1,
  },
  'typography.line-height.xl': {
    _original: {
      $value: 1.7,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.xl',
    $type: 'number',
    $value: 1.7,
  },
  'typography.line-height.xs': {
    _original: {
      $value: 1,
    },
    _group: {
      id: 'typography.line-height',
      $extensions: {
        requiredModes: [],
      },
      $type: 'number',
    },
    id: 'typography.line-height.xs',
    $type: 'number',
    $value: 1,
  },
};

export const modes = {
  'color.accent': {
    dark: '#ff3333',
  },
  'color.background': {
    dark: '#0a0a0a',
  },
  'color.btn.primary.bg': {
    dark: '#0054e5',
  },
  'color.btn.primary.border': {
    dark: '#0054e5',
  },
  'color.btn.primary.fg': {
    dark: 'white',
  },
  'color.btn.secondary.bg': {
    dark: 'transparent',
  },
  'color.btn.secondary.border': {
    dark: '#666',
  },
  'color.btn.secondary.fg': {
    dark: 'white',
  },
  'color.btn.tertiary.bg': {
    dark: '#f5f5f5',
  },
  'color.btn.tertiary.border': {
    dark: '#666',
  },
  'color.btn.tertiary.fg': {
    dark: 'black',
  },
  'color.surface': {
    dark: '#1a1a1a',
  },
  'color.text.muted': {
    dark: '#888888',
  },
  'color.text.primary': {
    dark: '#f5f5f5',
  },
  'color.text.secondary': {
    dark: '#b8b8b8',
  },
  'max-width.default': {
    zoomed: '125rem',
  },
  'max-width.thin': {
    zoomed: '62.5rem',
  },
  'transition.duration.fast': {
    reducedMotion: '0ms',
  },
  'transition.duration.normal': {
    reducedMotion: '0ms',
  },
  'transition.duration.slow': {
    reducedMotion: '0ms',
  },
  'typography.font-size.scale': {
    zoomed: 1.15,
  },
};

/** Get individual token */
export function token(tokenID, modeName) {
  if (modeName && modes[tokenID] && modeName in modes[tokenID]) return modes[tokenID][modeName];
  return tokens[tokenID];
}
