/**
 * Design Tokens
 * Autogenerated from tokens.json.
 * DO NOT EDIT!
 */

import {
  ParsedColorToken,
  ParsedDimensionToken,
  ParsedDurationToken,
  ParsedFontFamilyToken,
  ParsedNumberToken,
} from '@cobalt-ui/core';

export declare const tokens: {
  'border.radius.lg': ParsedDimensionToken['$value'];
  'border.radius.md': ParsedDimensionToken['$value'];
  'border.radius.sm': ParsedDimensionToken['$value'];
  'border.width.lg': ParsedDimensionToken['$value'];
  'border.width.md': ParsedDimensionToken['$value'];
  'border.width.sm': ParsedDimensionToken['$value'];
  'color.black': ParsedColorToken['$value'];
  'color.brand.interactive': ParsedColorToken['$value'];
  'color.brand.interactive-dark': ParsedColorToken['$value'];
  'color.brand.primary': ParsedColorToken['$value'];
  'color.btn.link.bg': ParsedColorToken['$value'];
  'color.btn.link.border': ParsedColorToken['$value'];
  'color.btn.link.fg': ParsedColorToken['$value'];
  'color.btn.link.hover.fg': ParsedColorToken['$value'];
  'color.btn.primary.bg': ParsedColorToken['$value'];
  'color.btn.primary.border': ParsedColorToken['$value'];
  'color.btn.primary.fg': ParsedColorToken['$value'];
  'color.btn.primary.hover.bg': ParsedColorToken['$value'];
  'color.btn.primary.hover.border': ParsedColorToken['$value'];
  'color.btn.primary.hover.fg': ParsedColorToken['$value'];
  'color.btn.secondary.bg': ParsedColorToken['$value'];
  'color.btn.secondary.border': ParsedColorToken['$value'];
  'color.btn.secondary.fg': ParsedColorToken['$value'];
  'color.btn.secondary.hover.bg': ParsedColorToken['$value'];
  'color.btn.secondary.hover.border': ParsedColorToken['$value'];
  'color.btn.secondary.hover.fg': ParsedColorToken['$value'];
  'color.btn.tertiary.bg': ParsedColorToken['$value'];
  'color.btn.tertiary.border': ParsedColorToken['$value'];
  'color.btn.tertiary.fg': ParsedColorToken['$value'];
  'color.btn.tertiary.hover.bg': ParsedColorToken['$value'];
  'color.btn.tertiary.hover.border': ParsedColorToken['$value'];
  'color.btn.tertiary.hover.fg': ParsedColorToken['$value'];
  'color.gray.100': ParsedColorToken['$value'];
  'color.gray.300': ParsedColorToken['$value'];
  'color.gray.500': ParsedColorToken['$value'];
  'color.gray.600': ParsedColorToken['$value'];
  'color.gray.700': ParsedColorToken['$value'];
  'color.gray.800': ParsedColorToken['$value'];
  'color.gray.900': ParsedColorToken['$value'];
  'color.gray.dark': ParsedColorToken['$value'];
  'color.gray.light': ParsedColorToken['$value'];
  'color.gray.medium': ParsedColorToken['$value'];
  'color.theme.background.default': ParsedColorToken['$value'];
  'color.theme.background.surface': ParsedColorToken['$value'];
  'color.theme.border.default': ParsedColorToken['$value'];
  'color.theme.border.light': ParsedColorToken['$value'];
  'color.theme.text.muted': ParsedColorToken['$value'];
  'color.theme.text.primary': ParsedColorToken['$value'];
  'color.theme.text.secondary': ParsedColorToken['$value'];
  'color.white': ParsedColorToken['$value'];
  'max-width.default': ParsedDimensionToken['$value'];
  'max-width.medium': ParsedDimensionToken['$value'];
  'max-width.narrow': ParsedDimensionToken['$value'];
  'max-width.thin': ParsedDimensionToken['$value'];
  'space.lg': ParsedDimensionToken['$value'];
  'space.md': ParsedDimensionToken['$value'];
  'space.semantic.padding': ParsedDimensionToken['$value'];
  'space.sm': ParsedDimensionToken['$value'];
  'space.xl': ParsedDimensionToken['$value'];
  'space.xs': ParsedDimensionToken['$value'];
  'space.xxl': ParsedDimensionToken['$value'];
  'space.xxs': ParsedDimensionToken['$value'];
  'space.xxxl': ParsedDimensionToken['$value'];
  'space.xxxs': ParsedDimensionToken['$value'];
  'transition.duration.fast': ParsedDurationToken['$value'];
  'transition.duration.normal': ParsedDurationToken['$value'];
  'transition.duration.slow': ParsedDurationToken['$value'];
  'typography.font-family.body': ParsedFontFamilyToken['$value'];
  'typography.font-family.mono': ParsedFontFamilyToken['$value'];
  'typography.font-family.primary': ParsedFontFamilyToken['$value'];
  'typography.font-family.secondary': ParsedFontFamilyToken['$value'];
  'typography.font-size.btn.default': ParsedDimensionToken['$value'];
  'typography.font-size.btn.sm': ParsedDimensionToken['$value'];
  'typography.font-size.heading.1': ParsedDimensionToken['$value'];
  'typography.font-size.heading.2': ParsedDimensionToken['$value'];
  'typography.font-size.heading.3': ParsedDimensionToken['$value'];
  'typography.font-size.heading.4': ParsedDimensionToken['$value'];
  'typography.font-size.heading.5': ParsedDimensionToken['$value'];
  'typography.font-size.heading.6': ParsedDimensionToken['$value'];
  'typography.font-size.paragraph.1': ParsedDimensionToken['$value'];
  'typography.font-size.paragraph.2': ParsedDimensionToken['$value'];
  'typography.font-size.paragraph.3': ParsedDimensionToken['$value'];
  'typography.font-size.paragraph.4': ParsedDimensionToken['$value'];
  'typography.font-size.paragraph.5': ParsedDimensionToken['$value'];
  'typography.font-size.scale': ParsedNumberToken['$value'];
  'typography.font-weight.bold': ParsedNumberToken['$value'];
  'typography.font-weight.bolder': ParsedNumberToken['$value'];
  'typography.font-weight.lighter': ParsedNumberToken['$value'];
  'typography.font-weight.normal': ParsedNumberToken['$value'];
  'typography.letter-spacing.lg': ParsedDimensionToken['$value'];
  'typography.letter-spacing.md': ParsedDimensionToken['$value'];
  'typography.letter-spacing.sm': ParsedDimensionToken['$value'];
  'typography.letter-spacing.xl': ParsedDimensionToken['$value'];
  'typography.letter-spacing.xs': ParsedDimensionToken['$value'];
  'typography.letter-spacing.xxl': ParsedDimensionToken['$value'];
  'typography.line-height.lg': ParsedNumberToken['$value'];
  'typography.line-height.md': ParsedNumberToken['$value'];
  'typography.line-height.sm': ParsedNumberToken['$value'];
  'typography.line-height.xl': ParsedNumberToken['$value'];
  'typography.line-height.xs': ParsedNumberToken['$value'];
};

export declare const meta: {
  'border.radius.lg': ParsedDimensionToken;
  'border.radius.md': ParsedDimensionToken;
  'border.radius.sm': ParsedDimensionToken;
  'border.width.lg': ParsedDimensionToken;
  'border.width.md': ParsedDimensionToken;
  'border.width.sm': ParsedDimensionToken;
  'color.black': ParsedColorToken;
  'color.brand.interactive': ParsedColorToken;
  'color.brand.interactive-dark': ParsedColorToken;
  'color.brand.primary': ParsedColorToken;
  'color.btn.link.bg': ParsedColorToken;
  'color.btn.link.border': ParsedColorToken;
  'color.btn.link.fg': ParsedColorToken;
  'color.btn.link.hover.fg': ParsedColorToken;
  'color.btn.primary.bg': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.primary.bg'] } };
  'color.btn.primary.border': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.primary.border'] } };
  'color.btn.primary.fg': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.primary.fg'] } };
  'color.btn.primary.hover.bg': ParsedColorToken;
  'color.btn.primary.hover.border': ParsedColorToken;
  'color.btn.primary.hover.fg': ParsedColorToken;
  'color.btn.secondary.bg': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.secondary.bg'] } };
  'color.btn.secondary.border': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.secondary.border'] } };
  'color.btn.secondary.fg': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.secondary.fg'] } };
  'color.btn.secondary.hover.bg': ParsedColorToken;
  'color.btn.secondary.hover.border': ParsedColorToken;
  'color.btn.secondary.hover.fg': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.secondary.hover.fg'] } };
  'color.btn.tertiary.bg': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.tertiary.bg'] } };
  'color.btn.tertiary.border': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.tertiary.border'] } };
  'color.btn.tertiary.fg': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.tertiary.fg'] } };
  'color.btn.tertiary.hover.bg': ParsedColorToken & { $extensions: { mode: typeof modes['color.btn.tertiary.hover.bg'] } };
  'color.btn.tertiary.hover.border': ParsedColorToken;
  'color.btn.tertiary.hover.fg': ParsedColorToken;
  'color.gray.100': ParsedColorToken;
  'color.gray.300': ParsedColorToken;
  'color.gray.500': ParsedColorToken;
  'color.gray.600': ParsedColorToken;
  'color.gray.700': ParsedColorToken;
  'color.gray.800': ParsedColorToken;
  'color.gray.900': ParsedColorToken;
  'color.gray.dark': ParsedColorToken;
  'color.gray.light': ParsedColorToken;
  'color.gray.medium': ParsedColorToken;
  'color.theme.background.default': ParsedColorToken & { $extensions: { mode: typeof modes['color.theme.background.default'] } };
  'color.theme.background.surface': ParsedColorToken & { $extensions: { mode: typeof modes['color.theme.background.surface'] } };
  'color.theme.border.default': ParsedColorToken & { $extensions: { mode: typeof modes['color.theme.border.default'] } };
  'color.theme.border.light': ParsedColorToken & { $extensions: { mode: typeof modes['color.theme.border.light'] } };
  'color.theme.text.muted': ParsedColorToken & { $extensions: { mode: typeof modes['color.theme.text.muted'] } };
  'color.theme.text.primary': ParsedColorToken & { $extensions: { mode: typeof modes['color.theme.text.primary'] } };
  'color.theme.text.secondary': ParsedColorToken & { $extensions: { mode: typeof modes['color.theme.text.secondary'] } };
  'color.white': ParsedColorToken;
  'max-width.default': ParsedDimensionToken & { $extensions: { mode: typeof modes['max-width.default'] } };
  'max-width.medium': ParsedDimensionToken;
  'max-width.narrow': ParsedDimensionToken;
  'max-width.thin': ParsedDimensionToken & { $extensions: { mode: typeof modes['max-width.thin'] } };
  'space.lg': ParsedDimensionToken;
  'space.md': ParsedDimensionToken;
  'space.semantic.padding': ParsedDimensionToken;
  'space.sm': ParsedDimensionToken;
  'space.xl': ParsedDimensionToken;
  'space.xs': ParsedDimensionToken;
  'space.xxl': ParsedDimensionToken;
  'space.xxs': ParsedDimensionToken;
  'space.xxxl': ParsedDimensionToken;
  'space.xxxs': ParsedDimensionToken;
  'transition.duration.fast': ParsedDurationToken & { $extensions: { mode: typeof modes['transition.duration.fast'] } };
  'transition.duration.normal': ParsedDurationToken & { $extensions: { mode: typeof modes['transition.duration.normal'] } };
  'transition.duration.slow': ParsedDurationToken & { $extensions: { mode: typeof modes['transition.duration.slow'] } };
  'typography.font-family.body': ParsedFontFamilyToken;
  'typography.font-family.mono': ParsedFontFamilyToken;
  'typography.font-family.primary': ParsedFontFamilyToken;
  'typography.font-family.secondary': ParsedFontFamilyToken;
  'typography.font-size.btn.default': ParsedDimensionToken;
  'typography.font-size.btn.sm': ParsedDimensionToken;
  'typography.font-size.heading.1': ParsedDimensionToken;
  'typography.font-size.heading.2': ParsedDimensionToken;
  'typography.font-size.heading.3': ParsedDimensionToken;
  'typography.font-size.heading.4': ParsedDimensionToken;
  'typography.font-size.heading.5': ParsedDimensionToken;
  'typography.font-size.heading.6': ParsedDimensionToken;
  'typography.font-size.paragraph.1': ParsedDimensionToken;
  'typography.font-size.paragraph.2': ParsedDimensionToken;
  'typography.font-size.paragraph.3': ParsedDimensionToken;
  'typography.font-size.paragraph.4': ParsedDimensionToken;
  'typography.font-size.paragraph.5': ParsedDimensionToken;
  'typography.font-size.scale': ParsedNumberToken & { $extensions: { mode: typeof modes['typography.font-size.scale'] } };
  'typography.font-weight.bold': ParsedNumberToken;
  'typography.font-weight.bolder': ParsedNumberToken;
  'typography.font-weight.lighter': ParsedNumberToken;
  'typography.font-weight.normal': ParsedNumberToken;
  'typography.letter-spacing.lg': ParsedDimensionToken;
  'typography.letter-spacing.md': ParsedDimensionToken;
  'typography.letter-spacing.sm': ParsedDimensionToken;
  'typography.letter-spacing.xl': ParsedDimensionToken;
  'typography.letter-spacing.xs': ParsedDimensionToken;
  'typography.letter-spacing.xxl': ParsedDimensionToken;
  'typography.line-height.lg': ParsedNumberToken;
  'typography.line-height.md': ParsedNumberToken;
  'typography.line-height.sm': ParsedNumberToken;
  'typography.line-height.xl': ParsedNumberToken;
  'typography.line-height.xs': ParsedNumberToken;
};

export declare const modes: {
  'color.btn.primary.bg': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.primary.border': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.primary.fg': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.secondary.bg': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.secondary.border': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.secondary.fg': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.secondary.hover.fg': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.tertiary.bg': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.tertiary.border': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.tertiary.fg': {
    dark: ParsedColorToken['$value'];
  };
  'color.btn.tertiary.hover.bg': {
    dark: ParsedColorToken['$value'];
  };
  'color.theme.background.default': {
    dark: ParsedColorToken['$value'];
  };
  'color.theme.background.surface': {
    dark: ParsedColorToken['$value'];
  };
  'color.theme.border.default': {
    dark: ParsedColorToken['$value'];
  };
  'color.theme.border.light': {
    dark: ParsedColorToken['$value'];
  };
  'color.theme.text.muted': {
    dark: ParsedColorToken['$value'];
  };
  'color.theme.text.primary': {
    dark: ParsedColorToken['$value'];
  };
  'color.theme.text.secondary': {
    dark: ParsedColorToken['$value'];
  };
  'max-width.default': {
    zoomed: ParsedDimensionToken['$value'];
  };
  'max-width.thin': {
    zoomed: ParsedDimensionToken['$value'];
  };
  'transition.duration.fast': {
    reducedMotion: ParsedDurationToken['$value'];
  };
  'transition.duration.normal': {
    reducedMotion: ParsedDurationToken['$value'];
  };
  'transition.duration.slow': {
    reducedMotion: ParsedDurationToken['$value'];
  };
  'typography.font-size.scale': {
    zoomed: ParsedNumberToken['$value'];
  };
};

export declare function token<K extends keyof typeof tokens>(tokenID: K, modeName?: never): typeof tokens[K];
export declare function token<K extends keyof typeof modes, M extends keyof typeof modes[K]>(tokenID: K, modeName: M): typeof modes[K][M];
